import Foundation
import UIKit

struct PDFExportService: PDFExportServicing {
    func makePDF(project: RankingDraft, result: RankingResult, insight: InsightReportDraft?) throws -> URL {
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("ScoreWise-\(project.id)-\(Int(Date().timeIntervalSince1970)).pdf")

        try renderer.writePDF(to: url) { context in
            context.beginPage()
            var y: CGFloat = 32

            func draw(_ text: String, font: UIFont, color: UIColor = .label) {
                let attributes: [NSAttributedString.Key: Any] = [
                    .font: font,
                    .foregroundColor: color
                ]
                let rect = CGRect(x: 32, y: y, width: pageRect.width - 64, height: 200)
                let height = text.boundingRect(
                    with: CGSize(width: rect.width, height: .greatestFiniteMagnitude),
                    options: [.usesLineFragmentOrigin, .usesFontLeading],
                    attributes: attributes,
                    context: nil
                ).height
                text.draw(with: CGRect(x: rect.minX, y: rect.minY, width: rect.width, height: height + 6), options: .usesLineFragmentOrigin, attributes: attributes, context: nil)
                y += height + 14
            }

            draw("ScoreWise Decision Report", font: .boldSystemFont(ofSize: 26))
            draw("Project: \(project.title)", font: .systemFont(ofSize: 16))
            draw("Date: \(DateFormatter.localizedString(from: .now, dateStyle: .medium, timeStyle: .short))", font: .systemFont(ofSize: 14), color: .secondaryLabel)
            draw("Usage context: \(project.usageContext.rawValue.capitalized)", font: .systemFont(ofSize: 14), color: .secondaryLabel)
            if !project.contextNarrative.isEmpty {
                draw("Context Brief", font: .boldSystemFont(ofSize: 18))
                draw(project.contextNarrative, font: .systemFont(ofSize: 13))
            }
            if !project.contextAttachments.isEmpty {
                draw("Context Files: \(project.contextAttachments.map { $0.fileName }.joined(separator: ", "))", font: .systemFont(ofSize: 12), color: .secondaryLabel)
            }

            y += 8
            draw("Vendors", font: .boldSystemFont(ofSize: 18))
            for vendor in project.vendors {
                draw("• \(vendor.name)", font: .systemFont(ofSize: 14))
            }

            y += 8
            draw("Criteria + Weights", font: .boldSystemFont(ofSize: 18))
            for criterion in project.criteria {
                draw("• \(criterion.name): \(String(format: "%.1f", criterion.weightPercent))%", font: .systemFont(ofSize: 14))
            }

            y += 8
            draw("Final Scores", font: .boldSystemFont(ofSize: 18))
            for vendor in result.rankedVendors {
                draw("• \(vendor.vendorName): \(String(format: "%.2f", vendor.totalScore))/10", font: .systemFont(ofSize: 14))
            }

            if let winner = result.rankedVendors.first {
                draw("Winner: \(winner.vendorName)", font: .boldSystemFont(ofSize: 18))
            }

            draw("Confidence: \(String(format: "%.0f", result.confidenceScore * 100))%", font: .systemFont(ofSize: 14))

            if let insight {
                y += 8
                draw("AI Rationale", font: .boldSystemFont(ofSize: 18))
                draw(insight.summary, font: .systemFont(ofSize: 14))
                draw(insight.winnerReasoning, font: .systemFont(ofSize: 14))

                draw("Risk Flags", font: .boldSystemFont(ofSize: 16))
                insight.riskFlags.forEach { draw("• \($0)", font: .systemFont(ofSize: 14)) }

                draw("Overlooked Strategic Points", font: .boldSystemFont(ofSize: 16))
                insight.overlookedStrategicPoints.forEach { draw("• \($0)", font: .systemFont(ofSize: 14)) }
            }

            draw("Generated by ScoreWise", font: .italicSystemFont(ofSize: 12), color: .secondaryLabel)
        }

        return url
    }
}
